; Sailboat black water tank monitor for a classic ESP32 DevKit / ESP32-WROOM-32D

[platformio]
default_envs = esp32dev

[env]
monitor_speed = 115200

[esp32_base]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
upload_speed = 921600
board_build.partitions = min_spiffs.csv
build_unflags =
  -Werror=reorder
monitor_filters = esp32_exception_decoder

[env:esp32dev]
extends = esp32_base
lib_deps =
  https://github.com/SignalK/SensESP.git#v3.1.0
lib_ignore =
  esp_websocket_client
build_src_filter =
  +<main.cpp>
  -<sensor_test.cpp>
build_flags =
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
  -D USE_ESP_IDF_LOG
  -D TAG='"Arduino"'

[env:esp32dev-test]
extends = esp32_base
build_src_filter =
  -<main.cpp>
  +<sensor_test.cpp>

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_flags =
  -std=c++17
  -I include
